backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "exams"
    label: "Exams"
    folder: "content/exams"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Exam Title", name: "title", widget: "string" }
      - { label: "Exam Code", name: "code", widget: "string" }
      - { label: "Duration (minutes)", name: "duration", widget: "number" }
      - { label: "Question PDF", name: "pdf", widget: "file" }